config/routes.rb
Akart2::Application.routes.draw do

  devise_for :users

  root :to => 'static_pages#home'
  resources :categories
  
  resources :products 
  resources :currency_types
  

  match '/help',              to: 'static_pages#help',                               via: 'get'
  match '/contact',           to: 'static_pages#contact',                            via: 'get'
  match '/about',             to: 'static_pages#about',                              via: 'get'
  match '/profile',           to: 'profiles#edit',        :as => :profile,           via: 'get'
  match '/profile',           to: 'profiles#update',      :as => :profile,           via: 'put'
  match '/cart_items',        to: 'cart_items#create',    :as => :cart_items,        via: 'post'
  match '/cart_item/:id',     to: 'cart_items#destroy',   :as => :destroy_cart_item, via: 'post'
  match '/cart',              to: 'carts#show',           :as => :cart,              via: 'get'
  match '/cart',              to: 'carts#update',         :as => :cart,              via: 'put'
  match '/createwallet/:id',  to: 'profiles#createwallet',:as => :create_wallet,     via: 'post'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :total

  has_many :cart_items, :dependent => :destroy

  def updateTotal
  	total = 0
  	self.cart_items.each do |ci|
  		total += ci.price
  	end
  	self.total = total
  	self.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	authorize_resource :class => false
	
	def show
		@cart = current_cart
	end

	def update
		@cart = current_cart
		if !params[:cart_item].nil? 
			params[:cart_item].each do |key, value|
				cart_item = CartItem.find(key)
				cart_item.quantity = value
				cart_item.calculateTotal
				cart_item.save
			end
		end
		@cart.updateTotal
		flash[:success] = "Cart updated successfully"
		redirect_to cart_path
	end
end

app/views/carts/show.html.erb
<% provide(:title, "Cart") %>

<div class="cart">
  <div class="container">
    <div class="row">
      <div class="span12">
				<h3 class="title"><i class="icon-shopping-cart"></i> Cart</h3>
        <br />

					<%= form_for @cart,  :as => :cart, :url => cart_path, 
                        :method => :put, :html => { :class => "row"} do |f| %>

		        <table class="table table-striped tcart">
							<thead>
		           	<tr>
			            <th class="span2"><p>Quantity</p></th>
			            <th><p>Name</p></th>
			            <th class="span2"><p class="text-right">Unit Price</p></th>
			            <th class="span2"><p class="text-right">Total</p></th>
			          </tr>
			        </thead>

		          <tbody>

								<% @cart.cart_items.each do |cart_item| %>

			            <tr>
			              <td>
												<%= number_field "cart_item", cart_item.id,  	:class => "input-mini", 
	    																															:value => cart_item.quantity, 
	    																															:min => "1" %>
											<div class="row span2">
												<%= link_to destroy_cart_item_path(cart_item), :method => :destroy,
																																		 :class => "btn btn-inverse" do %>
													<i class="icon-remove"></i>
												<% end %>
											</div>
			              </td>
			              <td>
											<%= link_to cart_item.product.name, product_path(cart_item.product) %>
											<% if !cart_item.variants.empty? %>
												<ul>
													<% cart_item.variants.each do |v| %>
														<li><%= "#{v.name} (#{number_to_currency v.price})" %></li>
													<% end %>
												</ul>
											<% end %>
			              </td>
			              <td>
											<p class="text-right">
												<%= number_to_currency(cart_item.price/cart_item.quantity) %>
												<br />
												<%= number_with_precision (usd_to_btc(cart_item.price/cart_item.quantity)), :precision => 4 %> BTC
												<br />
												<%= number_with_precision (usd_to_ltc(cart_item.price/cart_item.quantity)), :precision => 4 %> LTC&nbsp;
											</p>
			              </td>
			              <td>
											<p class="text-right">
												<%= number_to_currency cart_item.price %>
												<br />
												<%= number_with_precision (usd_to_btc cart_item.price), :precision => 4 %> BTC
												<br />
												<%= number_with_precision (usd_to_ltc cart_item.price), :precision => 4 %> LTC&nbsp;
											</p>
			              </td>
			            </tr>

			          <% end %>

		            <tr>
		              <th></th>
		              <th></th>
		              <th><p class="text-right">Total</p></th>
		              <th>
										<p class="text-right">
											<%= number_to_currency @cart.total %>
											<br />
											<%= number_with_precision (usd_to_btc @cart.total), :precision => 4 %> BTC
											<br />
											<%= number_with_precision (usd_to_ltc @cart.total), :precision => 4 %> LTC&nbsp;
										</p>
		              </th>
		            </tr>
		          </tbody>
		        </table>

          <div class="row">
            <div class="span4 offset8">
              <div class="pull-right">
              	<%= f.submit "Update cart", class: "btn" %> 
              </div>
            </div>
          </div>

				<% end %>

          <div class="row">
            <div class="span4 offset8">
              <div class="pull-right">
                <%= link_to "Checkout", "#", class: "btn btn-success" %>
              </div>
            </div>
          </div>

      </div>
    </div>
  </div>
</div>