config/routes.rb
Akart2::Application.routes.draw do

  devise_for :users

  root :to => 'static_pages#home'
  resources :categories
  
  resources :products 
  resources :currency_types
  

  match '/help',              to: 'static_pages#help',                               via: 'get'
  match '/contact',           to: 'static_pages#contact',                            via: 'get'
  match '/about',             to: 'static_pages#about',                              via: 'get'
  match '/profile',           to: 'profiles#edit',        :as => :profile,           via: 'get'
  match '/profile',           to: 'profiles#update',      :as => :profile,           via: 'put'
  match '/cart_items',        to: 'cart_items#create',    :as => :cart_items,        via: 'post'
  match '/cart_item/:id',     to: 'cart_items#destroy',   :as => :destroy_cart_item, via: 'post'
  match '/cart',              to: 'carts#show',           :as => :cart,              via: 'get'
  match '/cart',              to: 'carts#update',         :as => :cart,              via: 'put'
  match '/createwallet/:id',  to: 'profiles#createwallet',:as => :create_wallet,     via: 'post'

end

app/models/category.rb
class Category < ActiveRecord::Base
	default_scope order('category_order ASC, name ASC')

  has_many :products, dependent: :destroy
  has_one :image, :dependent => :destroy

	accepts_nested_attributes_for :image

  attr_accessible :name, :category_order, :visible, :image_attributes

  validates :name, :presence => true
  validates :category_order, :presence => true
  validates :image, :presence => true

  resourcify

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	load_and_authorize_resource

	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
		@products = @category.products
	end

	def edit
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
		@category.build_image
		@category.visible = true
	end

	def create
		@category = Category.new(params[:category])
		if @category.save
			flash[:success] = "Category created successfully"
			redirect_to @category
		else
			@category.build_image
			render 'new'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		flash[:success] = "Category deleted"
		redirect_to categories_path
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category])
			redirect_to @category
			flash[:success] = "Successfully saved category information"
		else
			render 'edit'
			flash[:fail] = "Could not save the category information"
		end
	end
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal"} do |f| %>
  <%= render 'shared/category_error_messages' %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xxlarge" %>
    </div>
  </div>

  <%= f.fields_for :image, :html => {:multipart => true} do |asset| %>
    <div class="control-group"> 
      <%= f.label :image, :class => "control-label" %>
      <div class="controls">
        <%= asset.file_field :image, :id => "file" %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :category_order, :class => "control-label" %>
    <div class="controls">
      <%= f.number_field :category_order, :class => "input-large" %>
    </div>
  </div>

    <div class="controls">
      <%= f.label :visible, :class => "checkbox" do %>
        <%= f.check_box :visible, { checked: @category.visible } %> Visible
      <% end %>
    </div>
  <hr>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>

<div class="items">
  <div class="container">
    <div class="row">
      <div class="span9">
        <h5 class="title">Edit <%= @category.name %></h5>
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>

<div class="items">
  <div class="container">
    <div class="row">

   		<div class="span12">
   			<h4 class="pull-left">Categories</h4>
   			<div class="clearfix"></div>
   			<div class="row">
   				<% @categories.each do |category| %>
            <div class="span3">
              <div class="item">
                <div class="item-image">
                	<%= link_to category do %>
										<%= image_tag category.image.image.url(:main) %>
                  <% end %>
                </div> 
								<div class="item-details">
	                <h5><%= link_to category.name, category %></h5>
	                <div class="clearfix"></div>
	                <hr />
	                <div class="button pull-right">
	                	<%= link_to "See more...", category %>
	                </div>
	                <div class="clearfix"></div>
                </div>  	
             	</div>
            </div>

   				<% end %>
   			</div>

				<% if (current_user) && (current_user.has_role? :admin) %>
				<%= link_to "New category", new_category_path, 
														:class => "btn btn-success icon" %>
				<% end %>
   		</div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>
<div class="items">
  <div class="container">
    <div class="row">
      <div class="span9">
        <h5 class="title">New Category</h5>
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>

<div class="items">
  <div class="container">
    <div class="row">

   		<div class="span12">
   			<h4 class="pull-left"><%= @category.name %></h4>
   			<div class="clearfix"></div>
   			<div class="row">
   				<% @products.each do |product| %>
						<%= render "shared/product", :product => product %>
   				<% end %>
   			</div>

				<% if (current_user) && (current_user.has_role? :admin) %>
					<hr>
					<%= link_to "New product", new_product_path(:cat_id => @category),
														:class => "btn btn-success icon" %>
					<%= link_to "Edit", edit_category_path(@category), 
														:class => "btn btn-primary icon" %>
					<%= link_to "Delete", @category,
														:method => :delete,
														:class => "btn btn-danger icon",
														:confirm => "Are you sure?" %>
				<% end %>
   		</div>
    </div>
  </div>
</div>