config/routes.rb
Akart2::Application.routes.draw do

  devise_for :users

  root :to => 'static_pages#home'
  resources :categories
  
  resources :products 
  resources :currency_types
  

  match '/help',              to: 'static_pages#help',                               via: 'get'
  match '/contact',           to: 'static_pages#contact',                            via: 'get'
  match '/about',             to: 'static_pages#about',                              via: 'get'
  match '/profile',           to: 'profiles#edit',        :as => :profile,           via: 'get'
  match '/profile',           to: 'profiles#update',      :as => :profile,           via: 'put'
  match '/cart_items',        to: 'cart_items#create',    :as => :cart_items,        via: 'post'
  match '/cart_item/:id',     to: 'cart_items#destroy',   :as => :destroy_cart_item, via: 'post'
  match '/cart',              to: 'carts#show',           :as => :cart,              via: 'get'
  match '/cart',              to: 'carts#update',         :as => :cart,              via: 'put'
  match '/createwallet/:id',  to: 'profiles#createwallet',:as => :create_wallet,     via: 'post'

end

app/models/product.rb
class Product < ActiveRecord::Base
	before_destroy :ensure_not_referenced_by_any_cart_item
	default_scope order('name ASC')

  resourcify

  belongs_to :category
  has_many :variant_categories, :dependent => :destroy
  has_many :cart_items

  has_one :slider_image, :dependent => :destroy, 
          :class_name => "Image", :foreign_key => "product_slider_id"
  has_one :main_image, :dependent => :destroy,
          :class_name => "Image", :foreign_key => "product_main_id"
  has_many :additional_images, :dependent => :destroy,  :class_name => "Image", 
                                                        :foreign_key => "product_additional_id"

  attr_accessible :category_id, :description, :name, :price, :sku, :visible, 
                  :variant_categories_attributes, :slider_image_attributes,
                  :main_image_attributes, :additional_images_attributes

  validates :name, :description, :category_id, :presence => true
  validates :price, :presence => true, :numericality => { :greater_than_or_equal_to => 0.01 }
  validates :main_image, :presence => true

  accepts_nested_attributes_for :variant_categories, 
    :reject_if => lambda { |a| a[:name].blank? },
  	:allow_destroy => true

  accepts_nested_attributes_for :additional_images, 
    :reject_if => lambda { |t| t[:image].nil? },
    :allow_destroy => true

  accepts_nested_attributes_for :slider_image
  accepts_nested_attributes_for :main_image

  private
  	def ensure_not_referenced_by_any_cart_item
  		if cart_items.empty?
  			return true
  		else
  			errors.add(:base, 'This product is in a cart')
  			return false
  		end
  	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	load_and_authorize_resource
	
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
		@product.build_slider_image if @product.slider_image.nil?
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to @product
			flash[:success] = "Successfully saved product information"
		else
			render 'edit'
			flash[:fail] = "Could not save the product information"
		end
	end

	def new
		@product = Product.new
		@product.visible = true
		@product.variant_categories.build
		@product.variant_categories.first.variants.build
		@product.build_main_image
		@product.build_slider_image
		@product.additional_images.build
	end

	def create
		@product = Product.new(params[:product])

		if @product.save
			flash[:success] = "Product created successfully"
			redirect_to @product
		else
			render 'new'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@category = @product.category
		@product.destroy
		flash[:success] = "Product successfully deleted"
		redirect_to @category
	end
end

app/views/products/_error_messages.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@product.errors.count, "error") %>.
    </div>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= nested_form_for @product, :html => { :class => "form-horizontal"} do |f| %>
  <%= render 'error_messages' %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xxlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :sku, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :sku, :class => "input-xxlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class => "input-xxlarge", :rows => 3 %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category_id, :class => "control-label" %>
    <div class="controls">
      <%= collection_select(:product, :category_id, Category.all, :id, :name, 
                            { :prompt => 'Please select a category',
                              :selected => params[:cat_id] }, 
                            { :class => "input-xxlarge" }) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :price, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :price, :class => "input-xxlarge" %>
    </div>
  </div>

  <div class="controls">
    <%= f.label :visible, :class => "checkbox" do %>
      <%= f.check_box :visible, { checked: @product.visible } %> Visible
    <% end %>
  </div>

  <hr>

  <%= f.fields_for :main_image, :html => {:multipart => true} do |asset| %>
    <div class="control-group"> 
      <%= f.label :main_image, :class => "control-label" %>
      <div class="controls">
        <%= asset.file_field :image, :id => "file" %>
      </div>
    </div>
  <% end %>

  <%= f.fields_for :slider_image, :html => {:multipart => true} do |asset| %>
    <div class="control-group"> 
      <%= f.label :slider_image, :class => "control-label" %>
      <div class="controls">
        <%= asset.file_field :image, :id => "file" %>
      </div>
    </div>
  <% end %>

  <%= f.fields_for :additional_images do |image| %>
    <%= render "images", :f => image %>
  <% end %>

  <p>
    <%= f.link_to_add :additional_images, :class => "btn" do %>
      New image
    <% end %>
  </p>

  <hr>

  <div class="controls">
    <p class="text-info"><strong>Variant categories and variants (optional)</strong></p>
  </div>

  <%= f.fields_for :variant_categories do |variant_category| %>
  	<%= render "var_cat", :f => variant_category %>
  <% end %>

  <p>
    <%= f.link_to_add :variant_categories, :class => "btn" do %>
      New variant category
    <% end %>
  </p>

  <%= f.submit "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/products/_images.html.erb
<div class="control-group"> 
  <%= f.label :additional_image, :class => "control-label" %>
  <div class="controls">
    <%= f.file_field :image, :id => "file" %>
  </div>
</div>

app/views/products/_product.html.erb
<%= form_for @product,  :as => :product, :url => cart_items_path(:product_id => @product), 
                        :method => :post, :html => { :class => "form-horizontal"} do |f| %>
	<%= render 'error_messages' %>

	<% @product.variant_categories.each do |vc| %>
		<strong><%= vc.name %></strong>

		<% vc.variants.each do |v| %>
			<%= f.label v.name, :class => "radio" do %>

			<%= radio_button "variant", vc.id, v.id, :checked => (v == vc.variants.first) %>
			<%= "#{v.name } (#{number_to_currency v.price})" %>

			<% end %>
		<% end %>
		<br />
	<% end %>

	  <%= f.label "Quantity", :class => "control-label" do %>
    	Quantity: <%= number_field "cart_item", "quantity", :class => "input-small", 
    																											:value => "1", :min => "1" %>
		<% end %>
	<%= f.submit "Add to cart", class: "btn btn-success icon pull-right" %>

<% end %>

app/views/products/_var_cat.html.erb
<hr>
<div class="control-group">
  <%= f.label "Variant category name", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class => "input-xxlarge" %>
    <%= f.link_to_remove :class => "btn" do %>
			Delete variant category
		<% end %>
  </div>
</div>

<div class="control-group">
  <%= f.label :variant_category_order, :class => "control-label" %>
  <div class="controls">
    <%= f.number_field :variant_category_order, :class => "input-large" %>
  </div>
</div>

<div class="controls">
  <%= f.label :visible, :class => "checkbox" do %>
    <%= f.check_box :visible, { checked: true } %> Visible
  <% end %>
</div>

<br /><br />

<%= f.fields_for :variants do |variant| %>
  <%= render 'variant_form', :f => variant %>
<% end %>

<p>
	<%= f.link_to_add :variants, :class => "btn" do %>
		New variant
	<% end %>
</p>
<hr>

app/views/products/_variant_form.html.erb
<div class="control-group">
  <%= f.label "Variant name", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class => "input-xxlarge" %>
    <%= f.link_to_remove :class => "btn" do %>
			Delete variant
		<% end %>
  </div>
</div>

<div class="control-group">
  <%= f.label "Variant price", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :price, :class => "input-large" %>
  </div>
</div>

<div class="controls">
  <%= f.label :default, :class => "checkbox" do %>
    <%= f.check_box :default %> Default
  <% end %>
</div>

<div class="controls">
  <%= f.label :visible, :class => "checkbox" do %>
    <%= f.check_box :visible, { checked: true } %> Visible
  <% end %>
</div>
<br />

app/views/products/edit.html.erb
<% provide(:title, "Edit Product") %>
<div class="items">
  <div class="container">
    <div class="row">
      <div class="span9">
        <h5 class="title">Edit <%= @product.name %></h5>
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, "Products") %>

<div class="items">
  <div class="container">
    <div class="row">

   		<div class="span12">
   			<h4 class="pull-left">All Products</h4>
   			<div class="clearfix"></div>
   			<div class="row">
   				<% @products.each do |product| %>
						<%= render "shared/product", :product => product %>
   				<% end %>
   			</div>

				<% if (current_user) && (current_user.has_role? :admin) %>
					<hr>
					<%= link_to "New product", new_product_path, :class => "btn btn-success icon" %>
				<% end %>
   		</div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, "New Product") %>
<div class="items">
  <div class="container">
    <div class="row">
      <div class="span9">
        <h5 class="title">New Product</h5>
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<div class="items">
  <div class="container">
    <div class="row">
      <%= render 'layouts/sidebar' %>
      <div class="span9">

        <div class="product-main">
          <div class="row">
            <div class="span4">

              <!-- Image. Flex slider -->
                <div class="product-slider">
                  <div class="product-image-slider flexslider">
                    <ul class="slides">
                        <!-- Each slide should be enclosed inside li tag. -->
                      <li>
                        <%= link_to @product.main_image.image.url(:popout), :class => "gallery", 
                                              :data => { :colorbox => true } do %>
                          <%= image_tag @product.main_image.image.url(:main) %>
                        <% end %> 
                      </li>

                      <% @product.additional_images.each do |image| %>
                        <li>
                          <%= link_to image.image.url(:popout), :class => "gallery", 
                                                                :data => { :colorbox => true } do %>
                            <%= image_tag image.image.url(:main) %>
                          <% end %>
                        </li> 
                      <% end %>
                    </ul>
                  </div>
              </div>

            </div>
            <div class="span5">
              <!-- Title -->
                <h4 class="title"><%= @product.name %></h4>
                <h5>Price : <%= number_to_currency @product.price %></h5>
                <p>SKU : <%= @product.sku %></p>

                <% if @product.variant_categories.empty? %>
                  <div class="input-append cart-quantity">
                    <%= form_for @product,  :as => :product, 
                                            :url => cart_items_path(:product_id => @product), 
                                            :method => :post, 
                                            :html => { :class => "form-horizontal"} do |f| %>
                      <%= number_field "cart_item", "quantity", :class => "input-mini", 
                                                                :value => "1", :min => "1" %>

                      <%= f.submit "Add to cart", class: "btn" %>
                    <% end %>
                  </div>
                  <% else %>
                    To order, please see the options tab
                  <% end %>

                <div class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_preferred_1"></a>
                <a class="addthis_button_preferred_2"></a>
                <a class="addthis_button_preferred_3"></a>
                <a class="addthis_button_preferred_4"></a>
                <a class="addthis_button_compact"></a>
                <a class="addthis_counter addthis_bubble_style"></a>
                </div>
                <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50e06de237d5cb9d"></script>
            </div>
          </div>
        </div>

<br />
        
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Description</a></li>
          <% if !@product.variant_categories.empty? %>
            <li><a href="#tab2" data-toggle="tab">Options</a></li>
          <% end %>
        </ul>

        <div class="tab-content">
          <div class="tab-pane active" id="tab1">
            <%= @product.description.html_safe %>
          </div>

          <% if !@product.variant_categories.empty? %>
            <div class="tab-pane" id="tab2">
              <%= form_for @product,  :as => :product, 
                                      :url => cart_items_path(:product_id => @product), 
                                      :method => :post, 
                                      :html => { :class => "form-horizontal"} do |f| %>
                <%= render 'error_messages' %>

                <% @product.variant_categories.each do |vc| %>
                  <strong><%= vc.name %></strong>

                  <% vc.variants.each do |v| %>
                    <%= f.label v.name, :class => "radio" do %>

                    <%= radio_button "variant", vc.id, v.id, :checked => (v == vc.variants.first) %>
                    <%= "#{v.name } (#{number_to_currency v.price})" %>

                    <% end %>
                  <% end %>
                  <br />
                <% end %>

                <%= number_field "cart_item", "quantity", :class => "input-small", 
                                                          :value => "1", :min => "1" %>
                <%= f.submit "Add to cart", class: "btn" %>
              <% end %>            
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>