config/routes.rb
Akart2::Application.routes.draw do

  devise_for :users

  root :to => 'static_pages#home'
  resources :categories
  
  resources :products 
  resources :currency_types
  

  match '/help',              to: 'static_pages#help',                               via: 'get'
  match '/contact',           to: 'static_pages#contact',                            via: 'get'
  match '/about',             to: 'static_pages#about',                              via: 'get'
  match '/profile',           to: 'profiles#edit',        :as => :profile,           via: 'get'
  match '/profile',           to: 'profiles#update',      :as => :profile,           via: 'put'
  match '/cart_items',        to: 'cart_items#create',    :as => :cart_items,        via: 'post'
  match '/cart_item/:id',     to: 'cart_items#destroy',   :as => :destroy_cart_item, via: 'post'
  match '/cart',              to: 'carts#show',           :as => :cart,              via: 'get'
  match '/cart',              to: 'carts#update',         :as => :cart,              via: 'put'
  match '/createwallet/:id',  to: 'profiles#createwallet',:as => :create_wallet,     via: 'post'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="span12">

            <div class="row">

              <div class="span4">
                <div class="widget">
                  <h5>Contact</h5>
                  <hr />
                    <div class="social">
                      <a href="#"><i class="icon-facebook facebook"></i></a>
                      <a href="#"><i class="icon-twitter twitter"></i></a>
                      <a href="#"><i class="icon-linkedin linkedin"></i></a>
                      <a href="#"><i class="icon-google-plus google-plus"></i></a> 
                    </div>
                  <hr />
                  <i class="icon-home"></i> &nbsp; 123, Some Area. Los Angeles, CA, 54321.
                  <hr />
                  <i class="icon-phone"></i> &nbsp; +239-3823-3434
                  <hr />
                  <i class="icon-envelope-alt"></i> &nbsp; <a href="mailto:#">someone@company.com</a>
                  <hr />
                  <div class="payment-icons">
                    <img src="/img/payment/americanexpress.gif" alt="" />
                    <img src="/img/payment/visa.gif" alt="" />
                    <img src="/img/payment/mastercard.gif" alt="" />
                    <img src="/img/payment/discover.gif" alt="" />
                    <img src="/img/payment/paypal.gif" alt="" />
                  </div>
                </div>
              </div>

              <div class="span4">
                <div class="widget">
                  <h5>About Us</h5>
                  <hr />
                   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum dolor eget nisi fermentum quis hendrerit magna vestibulum. Curabitur pulvinar ornare vulputate scelerisque scelerisque ut consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum dolor eget nisi fermentum quis hendrerit magna vestibulum.</p> 
                </div>
              </div>

              <div class="span4">
                <div class="widget">
                  <h5>Links Goes Here</h5>
                  <hr />
                  <div class="two-col">
                    <div class="col-left">
                      <ul>
                        <li><a href="#">Condimentum</a></li>
                        <li><a href="#">Etiam at</a></li>
                        <li><a href="#">Fusce vel</a></li>
                        <li><a href="#">Vivamus</a></li>
                        <li><a href="#">Pellentesque</a></li>
                        <li><a href="#">Vivamus</a></li>
                      </ul>
                    </div>
                    <div class="col-right">
                      <ul>
                        <li><a href="#">Condimentum</a></li>
                        <li><a href="#">Etiam at</a></li>
                        <li><a href="#">Fusce vel</a></li>
                        <li><a href="#">Vivamus</a></li>
                        <li><a href="#">Pellentesque</a></li>
                        <li><a href="#">Vivamus</a></li>
                      </ul>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </div>
              </div>
              
            </div>

            <hr />
            <!-- Copyright info -->
            <p class="copy">Copyright &copy; 2012 | <a href="#">Your Site</a> - <a href="#">Home</a> | <a href="#">About Us</a> | <a href="#">Service</a> | <a href="#">Contact Us</a></p>
      </div>
    </div>
  <div class="clearfix"></div>
  </div>
</footer>
<span class="totop">
	<a href="#">
		<i class="icon-chevron-up"></i>
	</a>
</span> 

app/views/layouts/_header.html.erb
<!-- Header starts -->
<header>
  <div class="container">
    <div class="row">

      <div class="span4">
        <!-- Logo. Use class "color" to add color to the text. -->
        <div class="logo">
          <h1><%= link_to ENV['store_title'], root_path, id: "logo" %></h1>
          <p class="meta">Open source shopping</p>
        </div>
      </div>

      <div class="span5 offset3">
        
        <!-- Search form -->
        <form class="form-search">
          <div class="input-append">
            <input class="span3" id="appendedInputButton" type="text" placeholder="Enter something to search">
            <button class="btn" type="button">Search</button>
          </div>
        </form>

        <div class="hlinks">
          <span>

            <!-- item details with price -->
            <%= link_to "#cart", :role => "button", :data => {:toggle => "modal"} do %>
              <%= pluralize current_cart.cart_items.count, 'item' %>
              <i class="icon-shopping-cart"></i>
              <span class="bold">
                <%= number_to_currency current_cart.total %>
              </span>  
            <% end %>
          </span>

          <!-- Login and Register link -->
          <span class="lr">
            <% if !user_signed_in? %>
              <%= link_to "Login", "#login", :role => "button", :data => {:toggle =>"modal"} %>
              |
              <%= link_to "Register", "#register", :role => "button", :data => {:toggle =>"modal"} %>
            <% else %>
              <%= link_to "Profile", profile_path %> | 
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
            <% end %>
          </span>
        </div>

      </div>

    </div>
  </div>
</header>
<!-- Header ends -->

app/views/layouts/_modal.html.erb
<!-- Cart Modal starts -->
<div id="cart" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h4>Shopping Cart</h4>
</div>
<div class="modal-body">

  <table class="table table-striped tcart">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% current_cart.cart_items.each do |cart_item| %>
        <tr>
          <td><%= link_to cart_item.product.name, cart_item.product %></td>
          <td><%= cart_item.quantity %></td>
          <td><%= number_to_currency cart_item.price %></td>
        </tr>
      <% end %>
      <tr>
        <th></th>
        <th>Total</th>
        <th><%= number_to_currency current_cart.total %></th>
      </tr>
    </tbody>
  </table>

</div>
<div class="modal-footer">
  <%= link_to "View cart", cart_path, :class => "btn" %>
  <%= link_to "Checkout", "#", :class => "btn btn-danger" %>
</div>
</div>

<!-- Cart modal ends -->

<!-- Login Modal starts -->
<div id="login" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4>Login</h4>
  </div>

  <div class="modal-body">

    <div class="form">

      <!-- Login form -->
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name),
                             :html => { :class => "form-horizontal" }) do |f| %>

        <div class="control-group">
          <%= f.label :email, :class => "control-label" %>
          <div class="controls">
            <%= f.email_field :email, :class => "input-large" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :password, :class => "control-label" %>
          <div class="controls">
            <%= f.password_field :password, :autocomplete => "off", :class => "input-large" %>
          </div>
        </div>

        <div class="controls">
          <%= f.label :remember_me, :class => "checkbox" do %>
            <%= f.check_box :remember_me %> Remember me
          <% end %>
        </div>

        <div class="form-actions">
          <%= f.submit "Sign in", :class => "btn" %>
        </div>
      <% end %>
    </div> 

  </div>
  <div class="modal-footer">
    <p>Dont have account? <%= link_to "Register", new_user_registration_path %> here.</p>
  </div>
</div>

<!-- Login modal ends -->

<!-- Register Modal starts -->

<div id="register" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4>Register</h4>
  </div>
  <div class="modal-body">
    <div class="form">
      <!-- Register form -->
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), 
                :html => { :class => "form-horizontal" } ) do |f| %>

          <div class="control-group">
            <%= f.label :email, :class => "control-label" %>
            <div class="controls">
              <%= f.email_field :email, :class => "input-large" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :password, :class => "control-label" %>
            <div class="controls">
              <%= f.password_field :password, :autocomplete => "off", :class => "input-large" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :password_confirmation, :class => "control-label" %>
            <div class="controls">
              <%= f.password_field :password_confirmation, :autocomplete => "off", :class => "input-large" %>
            </div>
          </div>
          
          <div class="form-actions">
             <%= f.submit "Sign up", :class => "btn" %>
          </div>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <p>Already have account? <%= link_to "Login", new_user_session_path %> here.</p>
  </div>
</div>

<!-- Register modal ends -->

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<div class="navbar">
 <div class="navbar-inner">
   <div class="container">
     <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
     </a>
     <div class="nav-collapse collapse">
       <ul class="nav">
         <li>
            <%= link_to root_path do %>
              <i class="icon-home"></i>
            <% end %>
          </li>
          <li class="dropdown">  
            <%= link_to categories_path,  :class => "dropdown-toggle", 
                                          :data => { :toggle => "dropdown" } do %>
              Shop
              <b class="caret"></b> 
            <% end %>
            <ul class="dropdown-menu"> 
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, category %></li>
              <% end %>
                <li><%= link_to "View all", categories_path %></li>
            </ul>  
          </li>            
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
       </ul>
     </div>
    </div>
 </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="span3 hidden-phone">

	<h5 class="title">Categories</h5>
	
	<nav>
	  <ul id="nav">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
	  </ul>
	</nav>
</div>

app/views/layouts/_slider.html.erb
<div class="container flex-main">
  <div class="row">
    <div class="span12">
            
      <div class="flex-image flexslider">
        <ul class="slides">
          <% Product.includes(:slider_image).where('images.product_slider_id IS NOT NULL').order('products.id DESC').limit(5).each do |product| %>
          
            <li>
              <%= image_tag product.slider_image.image.url(:slider) %>
              <div class="flex-caption">
                <h3><%= product.name %><h3>
                <p><%= truncate_html product.description, :length => 75 %></p>
                <div class="button">
                  <%= link_to "Buy", product %>
                </div>
              </div>
            </li>

          <% end %>          
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:400,600", :type =>"text/css" %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/modal' %>
    <%= render 'layouts/navbar' %>
    
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag "application" %>
  </body>
</html>